-- Rachel Bakes GF — launch-ready Supabase additions (run once in SQL editor)
-- Repo: bucksites. Used by waitlist-signup, contact-submit, custom-order-submit.

-- Notification waitlist: optional phone + structured interests
alter table public.waitlist add column if not exists phone text;
alter table public.waitlist add column if not exists interests jsonb;

-- General contact / order questions (no ordering gate)
create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  message text not null
);

-- Custom inquiries: split contact, reference notes, optional small file payload
alter table public.custom_orders add column if not exists email text;
alter table public.custom_orders add column if not exists phone text;
alter table public.custom_orders add column if not exists inspiration_notes text;
alter table public.custom_orders add column if not exists reference_file_name text;
alter table public.custom_orders add column if not exists reference_file_data text;

-- RLS: enable as needed; service role bypasses RLS for serverless inserts.

-- Preorder pickup windows (owner toggles in admin; customer sees only enabled options)
alter table public.config add column if not exists pickup_window_late_morning boolean not null default true;
alter table public.config add column if not exists pickup_window_afternoon boolean not null default true;
alter table public.config add column if not exists pickup_window_early_evening boolean not null default true;

-- Per-date preorder pickup (replaces global window toggles for customer UX; owner edits in admin)
alter table public.config add column if not exists preorder_pickup_schedule jsonb not null default '[]'::jsonb;

-- Payment preference (not processing — captured on submit)
alter table public.preorders add column if not exists payment_preference text;
alter table public.custom_orders add column if not exists payment_preference text;

-- Structured preorder line items (quantities per SKU); amount_cents = server-computed tentative total
alter table public.preorders add column if not exists line_items jsonb;
